const books = [
  {id:1,title:'The Little Cloud',grade:'K',time:'3 min',emoji:'☁️',deco:'🌤️',color:'#cfe8ed',pages:['The little cloud floats in the blue sky.','It sees a bird fly by.','The cloud makes soft rain for a flower.']},
  {id:2,title:'Max Finds a Friend',grade:'K',time:'4 min',emoji:'🐶',deco:'🦋',color:'#f8dfb9',pages:['Max is a small brown dog.','He meets a fox by the old log.','Now Max and the fox play all day.']},
  {id:3,title:'The Moon Garden',grade:'1',time:'5 min',emoji:'🌙',deco:'🌼',color:'#ccd4eb',pages:['Mia plants seeds beneath the moon.','Silver flowers begin to bloom.','Tiny moths dance around the garden.']},
  {id:4,title:'Sam’s Big Adventure',grade:'1',time:'6 min',emoji:'🚲',deco:'🌳',color:'#d9ebcc',pages:['Sam rides his bike down the path.','He crosses a bridge over a stream.','At sunset, Sam pedals safely home.']},
  {id:5,title:'The Secret Treehouse',grade:'2',time:'7 min',emoji:'🌳',deco:'🪜',color:'#e7d5b3',pages:['A secret treehouse waits in the woods.','Inside, we find a map and a lantern.','The map leads us to a sparkling pond.']},
  {id:6,title:'Luna and the Stars',grade:'2',time:'8 min',emoji:'🔭',deco:'⭐',color:'#d8d4eb',pages:['Luna watches the stars through her telescope.','She draws each bright shape in her notebook.','One day, Luna hopes to explore space.']},
  {id:7,title:'A Very Busy Bee',grade:'K',time:'3 min',emoji:'🐝',deco:'🌻',color:'#f8e6a9',pages:['Bee buzzes over the green hill.','She lands on a big yellow flower.','Then Bee carries pollen back home.']},
  {id:8,title:'The Kind Dragon',grade:'2',time:'7 min',emoji:'🐉',deco:'🏰',color:'#d4e7df',pages:['A gentle dragon lives beyond the castle.','He uses warm breath to bake village bread.','Everyone cheers for their helpful friend.']}
];

const grid=document.getElementById('book-grid');let activeBook=null,page=0,wordIndex=0,recognition=null,listening=false;
function gradeName(g){return g==='K'?'Kindergarten':`${g}${g==='1'?'st':'nd'} grade`}
function renderBooks(filter='all'){
  grid.innerHTML='';books.filter(b=>filter==='all'||b.grade===filter).forEach(book=>{
    const card=document.createElement('article');card.className='book-card';card.tabIndex=0;card.setAttribute('aria-label',`Read ${book.title}, ${gradeName(book.grade)}`);
    card.innerHTML=`<div class="book-cover" style="background:${book.color}"><span class="cloud-deco d1">${book.deco}</span><span class="scene">${book.emoji}</span><span class="cloud-deco d2">☁️</span></div><div class="book-info"><span class="level">${gradeName(book.grade)}</span><h3>${book.title}</h3><div class="book-meta"><span>◷ ${book.time} read</span><span class="read-arrow">→</span></div></div>`;
    card.addEventListener('click',()=>openBook(book));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openBook(book)}});grid.appendChild(card);
  });
}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');renderBooks(button.dataset.grade)}));
function openBook(book){activeBook=book;page=0;wordIndex=0;document.getElementById('reader').classList.add('open');document.getElementById('reader').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';renderPage()}
function renderPage(){stopListening();const words=activeBook.pages[page].split(' ');document.getElementById('story-grade').textContent=gradeName(activeBook.grade);document.getElementById('story-title').textContent=activeBook.title;document.getElementById('story-picture').style.background=activeBook.color;document.getElementById('story-picture').textContent=activeBook.emoji;document.getElementById('story-text').innerHTML=words.map((w,i)=>`<span class="word ${i<wordIndex?'done':i===wordIndex?'current':''}" data-word="${clean(w)}">${w}</span>`).join(' ');document.getElementById('page-label').textContent=`Page ${page+1} of ${activeBook.pages.length}`;document.getElementById('page-progress').style.width=`${((page+1)/activeBook.pages.length)*100}%`;document.getElementById('prev-page').disabled=page===0;document.getElementById('next-page').disabled=page===activeBook.pages.length-1;setStatus(wordIndex?'Great job! Keep going.':'Tap the microphone, then read the glowing word.')}
function clean(word){return word.toLowerCase().replace(/[^a-z']/g,'')}
function currentWord(){return document.querySelector('.word.current')?.dataset.word}
function advanceWord(){const words=activeBook.pages[page].split(' ');wordIndex++;if(wordIndex>=words.length){if(page<activeBook.pages.length-1){setStatus('Page complete! Moving to the next page…');setTimeout(()=>{page++;wordIndex=0;renderPage()},700)}else{stopListening();document.getElementById('celebration').classList.add('show');document.getElementById('celebration').setAttribute('aria-hidden','false')}return}renderPageWords();setStatus('That’s right! Read the next word.')}
function renderPageWords(){document.querySelectorAll('.word').forEach((el,i)=>{el.classList.toggle('done',i<wordIndex);el.classList.toggle('current',i===wordIndex)})}
function setStatus(text){document.querySelector('#speech-status span:last-child').textContent=text}
function startListening(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){setStatus('Speech recognition is not available here. Try Chrome or Edge.');return}recognition=new SpeechRecognition();recognition.lang='en-US';recognition.interimResults=true;recognition.continuous=true;recognition.onresult=e=>{let heard='';for(let i=e.resultIndex;i<e.results.length;i++)heard+=e.results[i][0].transcript+' ';const spoken=heard.toLowerCase().match(/[a-z']+/g)||[];if(spoken.includes(currentWord()))advanceWord();else if(e.results[e.results.length-1].isFinal)setStatus(`Try again — say “${currentWord()}”.`)};recognition.onerror=e=>{if(e.error!=='aborted')setStatus(e.error==='not-allowed'?'Please allow microphone access to read aloud.':'I didn’t catch that. Tap the microphone and try again.');stopListening()};recognition.onend=()=>{if(listening)try{recognition.start()}catch{stopListening()}};recognition.start();listening=true;document.getElementById('mic-button').classList.add('listening');document.querySelector('.mic-label').textContent='Listening…';document.getElementById('speech-status').classList.add('listening');setStatus(`Listening for “${currentWord()}”…`)}
function stopListening(){listening=false;if(recognition){recognition.onend=null;try{recognition.stop()}catch{}recognition=null}document.getElementById('mic-button').classList.remove('listening');document.querySelector('.mic-label').textContent='Start reading';document.getElementById('speech-status').classList.remove('listening')}
function speak(text){stopListening();if(!('speechSynthesis'in window)){setStatus('Read-aloud is not available in this browser.');return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.78;utterance.pitch=1.1;speechSynthesis.speak(utterance)}
function closeReader(){stopListening();window.speechSynthesis?.cancel();document.getElementById('reader').classList.remove('open');document.getElementById('reader').setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.getElementById('mic-button').addEventListener('click',()=>listening?stopListening():startListening());document.getElementById('try-word').addEventListener('click',()=>speak(currentWord()));document.getElementById('listen-story').addEventListener('click',()=>speak(activeBook.pages[page]));document.getElementById('close-reader').addEventListener('click',closeReader);document.getElementById('prev-page').addEventListener('click',()=>{if(page>0){page--;wordIndex=0;renderPage()}});document.getElementById('next-page').addEventListener('click',()=>{if(page<activeBook.pages.length-1){page++;wordIndex=0;renderPage()}});document.getElementById('celebration-close').addEventListener('click',()=>{document.getElementById('celebration').classList.remove('show');document.getElementById('celebration').setAttribute('aria-hidden','true');closeReader()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('celebration').classList.remove('show');closeReader()}});renderBooks();
